imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
        cookie_lifetime: 86400
        gc_maxlifetime: 86400

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        unix_socket: /var/run/mysqld/mysqld.sock
        options:
            1002: "SET NAMES UTF8"

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
            datetime_functions:
                day: Acme\CabinetBundle\Dql\Day
                month: Acme\CabinetBundle\Dql\Month
                year: Acme\CabinetBundle\Dql\Year

stof_doctrine_extensions:
    default_locale: ru_RU
    orm:
        default:
            timestampable: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Top10\CabinetBundle\Entity\User
    from_email:
        address:        cabinet@rimeks.ru
        sender_name:    Кабинет Оптовика
    registration:
        confirmation:
            enabled: true
        form:
            type: top10_user_registration

liip_imagine:
    filter_sets:
        thumb:
            quality: 100
            filters:
                thumbnail: { size: [100, 100], mode: inset }
        catalogfull:
            quality: 100
            filters:
                thumbnail: { size: [400, 300], mode: inset }